project:
  type: website
  output-dir: public
  render: 
    - "*.qmd"
    - "!README.md"

  resources:
    - "img/"

website:
  title: "George G. Vega Yon, Ph.D."
  image: img/logo.svg
  description: |
    Personal website of Doctor George G. Vega Yon, an Assistant Professor of Data Science at the University of Utah. Dr. Vega Yon works on Statistical Computing, Data Science, and Scientific Software Development.
  navbar:
    logo: img/logo.svg
    background: "#ff8000ff"
    foreground: white
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: software.qmd
        text: Software
      - href: talks.qmd
        text: Talks
      - href: teaching.qmd
        text: Teaching
      - text: 'Resume/CV'
        menu:
          - text: Resume (brief)
            href: https://raw.githubusercontent.com/gvegayon/resume/master/resume.pdf
          - text: CV (academic)
            href: https://raw.githubusercontent.com/gvegayon/resume/master/cv.pdf
    right:
      - href: https://github.com/gvegayon
        icon: github
      - href: https://linkedin.com/in/georgevegayon
        icon: linkedin
      - href: https://scholar.google.com/citations?user=34E1yTAAAAAJ&hl=en
        icon: mortarboard-fill
      - href: https://bsky.app/profile/gvegayon.bsky.social
        icon: bluesky
      - href: https://orcid.org/0000-0002-3171-0844
        text: ORCID
  google-analytics: UA-40608305-3

  page-footer:
    center: |
      Â© 2025 George G. Vega Yon. All rights reserved.

format:
  html:
    theme: 
      - default
    css: styles.css
    toc: false
    page-layout: article
    include-in-header: fontawesome.html

execute:
  freeze: auto