project:
  type: website
  output-dir: ../public/es
  render: 
    - "*.qmd"

  resources:
    - "../img/"

website:
  title: "George G. Vega Yon, Ph.D."
  image: ../img/logo.svg
  search: false
  description: |
    Sitio web personal del Doctor George G. Vega Yon, Profesor Asistente de Ciencia de Datos en la Universidad de Utah. El Dr. Vega Yon trabaja en ComputaciÃ³n EstadÃ­stica, Ciencia de Datos y Desarrollo de Software CientÃ­fico.
  navbar:
    logo: ../img/logo.svg
    background: "#ff8000ff"
    foreground: white
    collapse-below: lg
    left:
      - href: index.qmd
        text: Inicio
      - href: research.qmd
        text: InvestigaciÃ³n
      - href: software.qmd
        text: Software
      - href: talks.qmd
        text: Charlas
      - href: teaching.qmd
        text: EnseÃ±anza
      - text: 'CurrÃ­culum'
        menu:
          - text: Resume (breve)
            href: https://raw.githubusercontent.com/gvegayon/resume/master/resume.pdf
          - text: CV (acadÃ©mico)
            href: https://raw.githubusercontent.com/gvegayon/resume/master/cv.pdf
    right:
      - href: ../index.html
        text: ðŸ‡ºðŸ‡¸
      - href: ../zh/index.html
        text: ðŸ‡¨ðŸ‡³
      - href: https://github.com/gvegayon
        icon: github
      - href: https://linkedin.com/in/georgevegayon
        icon: linkedin
      - href: https://scholar.google.com/citations?user=34E1yTAAAAAJ&hl=en
        icon: mortarboard-fill
      - href: https://bsky.app/profile/gvegayon.bsky.social
        icon: bluesky
      - href: https://orcid.org/0000-0002-3171-0844
        text: ORCID
  google-analytics: G-FH7BRCRDTQ

  page-footer:
    center: |
      Â© 2025 George G. Vega Yon. Todos los derechos reservados.

format:
  html:
    theme: 
      - default
    css: ../styles.css
    toc: false
    page-layout: article

execute:
  freeze: auto
