project:
  type: website
  output-dir: ../public/zh
  render: 
    - "*.qmd"

  resources:
    - "../img/"

website:
  title: "George G. Vega Yon, Ph.D."
  image: ../img/logo.svg
  search: false
  description: |
    George G. Vega Yon åšå£«çš„å€‹äººç¶²ç«™ï¼ŒçŒ¶ä»–å¤§å­¸æ•¸æ“šç§‘å­¸åŠ©ç†æ•™æˆã€‚Vega Yon åšå£«å¾äº‹çµ±è¨ˆè¨ˆç®—ã€æ•¸æ“šç§‘å­¸å’Œç§‘å­¸è»Ÿä»¶é–‹ç™¼å·¥ä½œã€‚
  navbar:
    logo: ../img/logo.svg
    background: "#ff8000ff"
    foreground: white
    collapse-below: lg
    left:
      - href: index.qmd
        text: ä¸»é 
      - href: research.qmd
        text: ç ”ç©¶
      - href: software.qmd
        text: è»Ÿä»¶
      - href: talks.qmd
        text: æ¼”è¬›
      - href: teaching.qmd
        text: æ•™å­¸
      - text: 'ç°¡æ­·'
        menu:
          - text: Resume (ç°¡è¦)
            href: https://raw.githubusercontent.com/gvegayon/resume/master/resume.pdf
          - text: CV (å­¸è¡“)
            href: https://raw.githubusercontent.com/gvegayon/resume/master/cv.pdf
    right:
      - href: ../index.html
        text: ğŸ‡ºğŸ‡¸
      - href: ../es/index.html
        text: ğŸ‡ªğŸ‡¸
      - href: https://github.com/gvegayon
        icon: github
      - href: https://linkedin.com/in/georgevegayon
        icon: linkedin
      - href: https://scholar.google.com/citations?user=34E1yTAAAAAJ&hl=en
        icon: mortarboard-fill
      - href: https://bsky.app/profile/gvegayon.bsky.social
        icon: bluesky
      - href: https://orcid.org/0000-0002-3171-0844
        text: ORCID
  google-analytics: G-FH7BRCRDTQ

  page-footer:
    center: |
      Â© 2025 George G. Vega Yon. ç‰ˆæ¬Šæ‰€æœ‰ã€‚

format:
  html:
    theme: 
      - default
    css: ../styles.css
    toc: false
    page-layout: article

execute:
  freeze: auto
